import Header from "./header/header";
import React from "react";
import styles from "../styles/Home.module.css";
import Image from "next/image";
import Head from "next/head";
import {AppProvider} from "./context/AppContext";
import Footer from "./Footer";
import {gql} from "@apollo/client";
import client from "../components/ApolloClient";
import {Container} from "react-bootstrap";
import {ApolloProvider} from "@apollo/client";
import {ApolloProvider as ApolloHooksProvider} from "@apollo/react-hooks";
const Layout = (props) => {
    return (
        <>
            <ApolloProvider client={client}>
                <ApolloHooksProvider client={client}>
                    <Head>
                        <title>Ice Cold Lemon</title>
                        <meta name="description" content="Generated by create next app"/>
                        <link rel="icon" href="/favicon.ico"/>
                    </Head>
                    <Header/>
                    <main>
                    <Container fluid className={'main-content p-0 m-0'}>
                        {props.children}
                    </Container>
                    </main>
                    <Footer/>
                </ApolloHooksProvider>
            </ApolloProvider>

        </>
    )
}

export default Layout;
